### ISSUE TITLE
测试得运行这个脚本需要java环境，建议在md上补充

### ISSUE THREAD

**Issue by RJKKK** [lianzhh/EZBioCloud_ID_Selenium#1]
![image](https://user-images.githubusercontent.com/46342425/214799954-d3771e90-c5b0-4329-8753-29cbe4001b93.png)
这是代理服务的报错日志，需要java环境

**Comment by lianzhh** [comment]
感谢提醒，已经在md上补充！

**Comment by RJKKK** [comment]
感谢作者大大！

**Comment by RJKKK** [comment]
close
